# Generated by Django 4.1.1 on 2022-09-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gpa',
            field=models.FloatField(default=234),
            preserve_default=False,
        ),
    ]
